[package]
name = "lottery"
version = "0.0.2"
authors = [ "Alexis Davidson",]
edition = "2018"
publish = false

[lib]
path = "src/lottery.rs"

[dependencies.elrond-wasm]
version = "0.34.0"

[dev-dependencies.elrond-wasm-debug]
version = "0.34.0"
